apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: petapp-resources
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/sinchan62/petclinic-argocd.git
    targetRevision: test-env
    path: resources
  destination: 
    server: https://kubernetes.default.svc
    namespace: myapp

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true