---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pet-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pet-app
  template:
    metadata:
      labels:
        app: pet-app
    spec:
      containers:
      - name: pet-app
        image: rrohit62/petclinic-app:tagname
        ports:
        - name: petapp-port
          containerPort: 8080
        
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: pet-app-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: pet-app
  minReplicas: 1
  maxReplicas: 9
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50
  selector:
    matchLabels:
      app: pet-app  # Match the labels of the pods to autoscale
  template:
    metadata:
      labels:
        app: pet-app