apiVersion: apps/v1
kind: Deployment
metadata:
  name: pet-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: pet-app
  template:
    metadata:
      labels:
        app: pet-app
    spec:
      containers:
      - name: pet-app
        image: rrohit62/petclinic-app:latest
        ports:
        - name: petapp-port
          containerPort: 8080
