apiVersion: apps/v1
kind: Deployment
metadata:
  name: pet-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: pet-app
  template:
    metadata:
      labels:
        app: pet-app
    spec:
      containers:
      - name: pet-app
        image: sharath2787/petclinic:3
        ports:
        - name: petapp-port
          containerPort: 8080
        env:
              - name: MYSQL_URL
                value: "jdbc:mysql://db-petapp:3306/petclinic"
              - name: MYSQL_USER
                valueFrom:
                  secretKeyRef:
                    name: db-secret
                    key: pet-user
              - name: MYSQL_PASS
                valueFrom:
                  secretKeyRef:
                    name: db-secret
                    key: petUser-pass

      